package(default_visibility = ["//visibility:public"])

java_library(
    name = "prometheus",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/grpc:grpc_core",
        "//third_party/grpc:grpc_stub",
        "//third_party/prometheus",
    ],
)
