---
name: Install
runs:
  using: composite
  steps:
    - name: Install Bazel (linux)
      run: |
        wget 'https://github.com/bazelbuild/bazel/releases/download/3.4.0/bazel_3.4.0-linux-x86_64.deb'
        chmod +x bazel_3.4.0-linux-x86_64.deb
        sudo dpkg -i bazel_3.4.0-linux-x86_64.deb
      shell: bash

