java_test(
    name = "tests",
    size = "small",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/me/dinowernli/grpc/prometheus",
        "//src/main/java/me/dinowernli/grpc/prometheus/testing",
        "//src/main/proto:hello_proto_grpc",
        "//third_party/grpc",
        "//third_party/grpc:grpc_testing",
        "//third_party/guava",
        "//third_party/netty",
        "//third_party/prometheus",
        "//third_party/testing",
    ],
)
