java_test(
  name = "tests",
  srcs = glob(['*.java']),
  size = "small",
  deps = [
    "//src/main/java/com/github/dinowernli/grpc/prometheus",
    "//src/main/java/com/github/dinowernli/grpc/prometheus/testing",
    "//src/main/proto:hello_proto_grpc",
    "//third_party/grpc",
    "//third_party/guava",
    "//third_party/netty",
    "//third_party/prometheus:servlet",
    "//third_party/testing",
  ],
)
